version: '3.1'

services:

  horizon-db:
    image: postgres:13.4-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: horizon-db
    ports:
      - 5432:5432
    
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    depends_on:
      - horizon-db
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: horizon-db

  horizon-api:
    build: ./api
    restart: always
    depends_on:
      - horizon-db
    ports:
      - 5000:5000

  horizon-site:
    build: ./site
    restart: always
    depends_on:
      - horizon-api
    ports:
      - 8080:8080
