version: '3.1'

services:

  horizon-db:
    image: postgres
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: horizon-db
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  horizon-api:
    build: ./api
    restart: always
    depends_on:
      - horizon-db
    ports:
      - 5000:5000

  horizon-site:
    build: ./site
    restart: always
    depends_on:
      - horizon-api
    ports:
      - 8080:8080

volumes:
  dbdata: