name: Lint

on: [push]

jobs:
  lint-front:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci
        working-directory: site

      - name: Run ESLint and Prettier
        run: npm run format
        working-directory: site

  lint-back:
    name: Lint Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
        working-directory: api

      - name: Run ESLint
        run: npm run lint
        working-directory: api
